### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by loveboylion** [joseasoler/todds#19]
Can you make it so that we can set how many concurrent jobs can be run for conversion

**Comment by loveboylion** [comment]
lol just saw 
  -th, --threads        Number of threads used by the parallel pipeline, must be in [1, 32].
between what is the default value ?

**Comment by joseasoler** [comment]
By default todds uses the maximum number of threads available. I have modified todds' `--help` and README to include this information too.

`-th, --threads        Number of threads used by the parallel pipeline, must be in [1, 32]. Defaults to maximum.`
