### ISSUE TITLE
bitdenfender think todds is a virus

### ISSUE THREAD

**Issue by cylian914** [joseasoler/todds#20]
**Describe the bug**
bitdenfender think todds is a virus

**To Reproduce**
download todds

**System (please complete the following information):**
windows 11

**Additional context**
![image](https://github.com/joseasoler/todds/assets/73445993/4d22b1bb-8381-4b86-b818-4cdb4cbe7e2a)

im not the one who got the repport btw

**Comment by joseasoler** [comment]
todds cannot control how antivirus software will detect it. I recommend you use bitdefender's incorrect detection reports to pursue the issue with them.
